USE hexagone_sql;
CREATE TABLE user (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL
)ENGINE=InnoDB;

CREATE TABLE article (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    author_id INT(11) UNSIGNED NOT NULL,
    title VARCHAR(50) NOT NULL,
    CONSTRAINT FK_AUTHOR FOREIGN KEY (author_id) REFERENCES user(id)
)ENGINE=InnoDB;

CREATE TABLE comment (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    author_id INT(11) UNSIGNED NOT NULL,
    title VARCHAR(50) NOT NULL,
    CONSTRAINT FK_AUTHOR_COMMENT FOREIGN KEY (author_id) REFERENCES user(id),
    CONSTRAINT FK_AUTHOR_ARTICLE FOREIGN KEY (author_id) REFERENCES article(id)
)ENGINE=InnoDB;



